# This is a basic workflow to help you get started with Actions

name: Jiho

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hi:
    # INFO: need permission
    # https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Rutn auto labeler
        uses: ./ # Uses an action in the root directory
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
